insert into Tb_Professor(Nome_Professor, Foto_Professor, Video_Professor, Sexo_Professor, Email_Professor, Senha_Professor, Contato1_Professor, Contato2_Professor, CPF_Professor, DataNascimento_Professor, CEP_Professor, Endereco_Professor, NumeroEnd_Professor, ComplementoEnd_Professor, Bairro_Professor, Cidade_Professor, Estado_Professor, Segmento_Professor, Disciplina_Professor, Formacao_Professor, Valor_Aula_Professor, Descricao_Professor, Skype_Professor, Facebook_Professor, Linkedin_Professor, Youtube_Professor, Categoria) values('Antônio Oliveira','upload/professor/man-5.png','http://www.youtube.com/v/NZZpRJ6lIz4&hl=en&fs=1','Masculino','antonio@gmail.com','123','(21) 2074-3684','(21) 8715-4829','546.582.085-39','25/06/1984','23530-092','Beco Eunice','68','','Sepetiba','Rio de Janeiro','RJ','Ensino Fundamental','Português','Sou formado na UFRJ. Certificados de pedagogia.','120','Adoro dar aula, sou muito bom com crianças e adolescentes. Tenho uma didática diferenciada.','antonio','','','', 1)
Insert into Agenda (Id_Professor, Dia, Manha, Tarde, Noite) values (3, ' Domingo', ' 08:00 09:00', ' 13:00 15:00', ' 18:00 20:00')

insert into Tb_Professor(Nome_Professor, Foto_Professor, Video_Professor, Sexo_Professor, Email_Professor, Senha_Professor, Contato1_Professor, Contato2_Professor, CPF_Professor, DataNascimento_Professor, CEP_Professor, Endereco_Professor, NumeroEnd_Professor, ComplementoEnd_Professor, Bairro_Professor, Cidade_Professor, Estado_Professor, Segmento_Professor, Disciplina_Professor, Formacao_Professor, Valor_Aula_Professor, Descricao_Professor, Skype_Professor, Facebook_Professor, Linkedin_Professor, Youtube_Professor, Categoria) values('Carla Martins','upload/professor/woman-2.png','http://www.youtube.com/v/NZZpRJ6lIz4&hl=en&fs=1','Feminino','carla@gmail.com','123','(53) 9386-3618','(53) 7958-6514','144.792.297-28','13/12/1976','96207-260','Rua Passo Fundo','531','apto 24','Cassino','Rio Grande','RS','Pré-Vestibular','Física','Sou formado na UFRS. Certificados de pedagogia.','80','Adoro dar aula, sou muito bom com crianças e adolescentes. Tenho uma didática diferenciada.','carla','','','', 1)
Insert into Agenda (Id_Professor, Dia, Manha, Tarde, Noite) values (2, ' Sexta-Feira Sábado', ' 08:00 09:00', ' 13:00 17:00', ' 18:00 21:00')

insert into Tb_Professor(Nome_Professor, Foto_Professor, Video_Professor, Sexo_Professor, Email_Professor, Senha_Professor,  Contato1_Professor, Contato2_Professor, CPF_Professor, DataNascimento_Professor, CEP_Professor, Endereco_Professor,  NumeroEnd_Professor, ComplementoEnd_Professor, Bairro_Professor, Cidade_Professor, Estado_Professor, Segmento_Professor,  Disciplina_Professor, Formacao_Professor, Valor_Aula_Professor, Descricao_Professor, Skype_Professor, Facebook_Professor,  Linkedin_Professor, Youtube_Professor, Categoria) values('Vitor Cunha Souza','upload/professor/man-10.png','','Masculino','vitor.cunha@studify.com','123','(81) 3590-7293','(81) 8848-9847','455.456.966-79','24/06/1985','54780-370','Rua das  Tulipas','1158','','Alberto Maia','Camaragibe','PE','Ensino Médio','Química','Bacharelado','350','Tenho vontade de ensinar  a todos que queiram aprender Matemática, para que aumente o número de pessoas para o mercado de trabalho. Qualquer dúvida, email:  vitor.cunha@studiy.com','','','','', 1)
Insert into Agenda (Id_Professor, Dia, Manha, Tarde, Noite) values (1, ' Domingo Terça-Feira Sábado', ' 08:00 10:00', ' 14:00  16:00', ' 18:00 22:00')

insert into Tb_Professor(Nome_Professor, Foto_Professor, Video_Professor, Sexo_Professor, Email_Professor, Senha_Professor, Contato1_Professor, Contato2_Professor, CPF_Professor, DataNascimento_Professor, CEP_Professor, Endereco_Professor, NumeroEnd_Professor, ComplementoEnd_Professor, Bairro_Professor, Cidade_Professor, Estado_Professor, Segmento_Professor, Disciplina_Professor, Formacao_Professor, Valor_Aula_Professor, Descricao_Professor, Skype_Professor, Facebook_Professor, Linkedin_Professor, Youtube_Professor, Categoria) values('Letícia Santos','upload/professor/woman-5.png','http://www.youtube.com/v/NZZpRJ6lIz4&hl=en&fs=1','Feminino','leticia@gmail.com','123','(53) 9386-3618','(53) 7958-6514','279.481.789-29','13/12/1976','96207-260','Rua Passo Fundo','531','apto 24','Cassino','Rio Grande','RS','Ensino Fundamental','Matemática','Sou formado na UFRS. Certificados de pedagogia.','80','Adoro dar aula, sou muito bom com crianças e adolescentes. Tenho uma didática diferenciada.','leticia','','','', 1)
Insert into Agenda (Id_Professor, Dia, Manha, Tarde, Noite) values (2, ' Sexta-Feira Sábado', ' 08:00 09:00', ' 13:00 17:00', ' 18:00 21:00')

insert into Tb_Professor(Nome_Professor, Foto_Professor, Video_Professor, Sexo_Professor, Email_Professor, Senha_Professor, Contato1_Professor, Contato2_Professor, CPF_Professor, DataNascimento_Professor, CEP_Professor, Endereco_Professor, NumeroEnd_Professor, ComplementoEnd_Professor, Bairro_Professor, Cidade_Professor, Estado_Professor, Segmento_Professor, Disciplina_Professor, Formacao_Professor, Valor_Aula_Professor, Descricao_Professor, Skype_Professor, Facebook_Professor, Linkedin_Professor, Youtube_Professor, Categoria) values('Diogo Silva','upload/professor/man-5.png','http://www.youtube.com/v/NZZpRJ6lIz4&hl=en&fs=1','Masculino','diogo@gmail.com','123','(41) 3454-7113','(41) 7585-1864','587.324.911-31','12/04/1988','80620-380','Rua Coronel José Gomes do Amaral','68','','Sepetiba','Curitiba','PR','Ensino Técnico','Informática','Sou formado na UFPR. Certificados de pedagogia.','120','Adoro dar aula, sou muito bom com crianças e adolescentes. Tenho uma didática diferenciada.','diogo','','','', 1)
Insert into Agenda (Id_Professor, Dia, Manha, Tarde, Noite) values (3, ' Domingo', ' 08:00 09:00', ' 13:00 15:00', ' 18:00 20:00')

use Studify

delete from Tb_Professor

DBCC CHECKIDENT('Tb_Professor',RESEED, 0)

select * from Tb_Professor